variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: devops-acr-connection
  imageRepository: devopsweb1-repository
  containerRegistry: sarfarazproject
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:

- task: AzureWebAppContainer@1 # Description what the task will execute
  inputs:
    azureSubscription: 'devops-appservice-resource-group'
   # appName: 'appsvc_windows_centralus'
   #appName: 'devops-linux-appservice'
   appName: 'devops-webapp-test'
    containers: $(containerRegistry)/$(imageRepository):$(tag)
